require("dotenv").config()
const mongoose = require("mongoose")
const Problem = require("./models/Problems")
const connectDB = require("./config/db")

const problems = [
  // ── EASY (10) ──
  { title:"Two Sum",difficulty:"easy",description:"Given an array of integers and a target, return indices of two numbers that add up to the target.",tags:["Array","Hash Table"],examples:[{input:"4\n2 7 11 15\n9",output:"0 1"}],testCases:[{input:"4\n2 7 11 15\n9",output:"0 1"},{input:"3\n3 2 4\n6",output:"1 2"},{input:"2\n3 3\n6",output:"0 1"}],boilerplate:{javascript:"// Read input and find two indices\nconst lines = require('fs').readFileSync('/dev/stdin','utf8').trim().split('\\n');\nconst n = parseInt(lines[0]);\nconst arr = lines[1].split(' ').map(Number);\nconst target = parseInt(lines[2]);\n// Write your solution here",python:"import sys\nlines = sys.stdin.read().strip().split('\\n')\nn = int(lines[0])\narr = list(map(int, lines[1].split()))\ntarget = int(lines[2])\n# Write your solution here",cpp:"#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n; cin>>n;\n    vector<int> a(n);\n    for(int i=0;i<n;i++) cin>>a[i];\n    int t; cin>>t;\n    // Write your solution here\n    return 0;\n}"}},
  { title:"Reverse String",difficulty:"easy",description:"Given a string, return it reversed.",tags:["String"],examples:[{input:"hello",output:"olleh"}],testCases:[{input:"hello",output:"olleh"},{input:"world",output:"dlrow"},{input:"a",output:"a"},{input:"racecar",output:"racecar"}],boilerplate:{javascript:"const s = require('fs').readFileSync('/dev/stdin', 'utf8').trim();\n// Write your solution here\n",python:"s = input()\n# Write your solution here\n",cpp:"#include <iostream>\n#include <string>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    string s;\n    if (cin >> s) {\n        // Write your solution here\n    }\n    return 0;\n}"}},
  { title:"Palindrome Check",difficulty:"easy",description:"Check if a given string is a palindrome. Print 'true' or 'false'.",tags:["String"],examples:[{input:"racecar",output:"true"}],testCases:[{input:"racecar",output:"true"},{input:"hello",output:"false"},{input:"a",output:"true"},{input:"madam",output:"true"}],boilerplate:{javascript:"const s = require('fs').readFileSync('/dev/stdin', 'utf8').trim();\n// Write your solution here\n",python:"s = input()\n# Write your solution here\n",cpp:"#include <iostream>\n#include <string>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    string s;\n    if (cin >> s) {\n        // Write your solution here\n    }\n    return 0;\n}"}},
  { title:"Find Maximum",difficulty:"easy",description:"Given an array of integers, find and print the maximum element.",tags:["Array"],examples:[{input:"5\n1 3 5 2 4",output:"5"}],testCases:[{input:"5\n1 3 5 2 4",output:"5"},{input:"3\n-1 -5 -2",output:"-1"},{input:"1\n42",output:"42"}],boilerplate:{javascript:"const lines = require('fs').readFileSync('/dev/stdin', 'utf8').trim().split('\\n');\nif (lines.length >= 2) {\n    const n = parseInt(lines[0]);\n    const arr = lines[1].split(' ').map(Number);\n    // Write your solution here\n}",python:"import sys\n\ndef main():\n    lines = sys.stdin.read().strip().split('\\n')\n    if len(lines) >= 2:\n        n = int(lines[0])\n        arr = list(map(int, lines[1].split()))\n        # Write your solution here\n\nif __name__ == '__main__':\n    main()",cpp:"#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n;\n    if (cin >> n) {\n        vector<int> arr(n);\n        for (int i = 0; i < n; i++) {\n            cin >> arr[i];\n        }\n        // Write your solution here\n    }\n    return 0;\n}"}},
  { title:"Count Vowels",difficulty:"easy",description:"Count the number of vowels in a given string (case-insensitive).",tags:["String"],examples:[{input:"Hello World",output:"3"}],testCases:[{input:"Hello World",output:"3"},{input:"aeiou",output:"5"},{input:"bcdfg",output:"0"},{input:"AEIOU",output:"5"}],boilerplate:{javascript:"const s = require('fs').readFileSync('/dev/stdin', 'utf8').trim();\n// Write your solution here\n",python:"s = input()\n# Write your solution here\n",cpp:"#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    string s;\n    if (getline(cin, s)) {\n        // Write your solution here\n    }\n    return 0;\n}"}},
  { title:"Sum of Array",difficulty:"easy",description:"Given an array of integers, print their sum.",tags:["Array","Math"],examples:[{input:"4\n1 2 3 4",output:"10"}],testCases:[{input:"4\n1 2 3 4",output:"10"},{input:"3\n-1 0 1",output:"0"},{input:"1\n100",output:"100"}],boilerplate:{javascript:"const lines = require('fs').readFileSync('/dev/stdin', 'utf8').trim().split('\\n');\nif (lines.length >= 2) {\n    const n = parseInt(lines[0]);\n    const arr = lines[1].split(' ').map(Number);\n    // Write your solution here\n}",python:"import sys\n\ndef main():\n    lines = sys.stdin.read().strip().split('\\n')\n    if len(lines) >= 2:\n        n = int(lines[0])\n        arr = list(map(int, lines[1].split()))\n        # Write your solution here\n\nif __name__ == '__main__':\n    main()",cpp:"#include <iostream>\n#include <vector>\nusing namespace std;\n\nint main() {\n    int n;\n    if (cin >> n) {\n        vector<int> arr(n);\n        for (int i = 0; i < n; i++) {\n            cin >> arr[i];\n        }\n        // Write your solution here\n    }\n    return 0;\n}"}},
  { title:"Even or Odd",difficulty:"easy",description:"Given a number, print 'Even' or 'Odd'.",tags:["Math"],examples:[{input:"4",output:"Even"}],testCases:[{input:"4",output:"Even"},{input:"7",output:"Odd"},{input:"0",output:"Even"},{input:"-3",output:"Odd"}],boilerplate:{javascript:"const n = parseInt(require('fs').readFileSync('/dev/stdin', 'utf8').trim());\n// Write your solution here\n",python:"n = int(input())\n# Write your solution here\n",cpp:"#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    if (cin >> n) {\n        // Write your solution here\n    }\n    return 0;\n}"}},
  { title:"Fibonacci Number",difficulty:"easy",description:"Given n, print the nth Fibonacci number (0-indexed). F(0)=0, F(1)=1.",tags:["Math","DP"],examples:[{input:"6",output:"8"}],testCases:[{input:"6",output:"8"},{input:"0",output:"0"},{input:"1",output:"1"},{input:"10",output:"55"}],boilerplate:{javascript:"const n = parseInt(require('fs').readFileSync('/dev/stdin', 'utf8').trim());\n// Write your solution here\n",python:"n = int(input())\n# Write your solution here\n",cpp:"#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    if (cin >> n) {\n        // Write your solution here\n    }\n    return 0;\n}"}},
  { title:"Factorial",difficulty:"easy",description:"Given n, print n! (n factorial).",tags:["Math"],examples:[{input:"5",output:"120"}],testCases:[{input:"5",output:"120"},{input:"0",output:"1"},{input:"1",output:"1"},{input:"10",output:"3628800"}],boilerplate:{javascript:"const n = parseInt(require('fs').readFileSync('/dev/stdin', 'utf8').trim());\n// Write your solution here\n",python:"n = int(input())\n# Write your solution here\n",cpp:"#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    if (cin >> n) {\n        // Write your solution here\n    }\n    return 0;\n}"}},
  { title:"Remove Duplicates",difficulty:"easy",description:"Given a sorted array, print the array with duplicates removed, space-separated.",tags:["Array"],examples:[{input:"7\n1 1 2 2 3 4 4",output:"1 2 3 4"}],testCases:[{input:"7\n1 1 2 2 3 4 4",output:"1 2 3 4"},{input:"5\n1 1 1 1 1",output:"1"},{input:"3\n1 2 3",output:"1 2 3"}],boilerplate:{javascript:"const lines = require('fs').readFileSync('/dev/stdin', 'utf8').trim().split('\\n');\nif (lines.length >= 2) {\n    const n = parseInt(lines[0]);\n    const arr = lines[1].split(' ').map(Number);\n    // Write your solution here\n}",python:"import sys\n\ndef main():\n    lines = sys.stdin.read().strip().split('\\n')\n    if len(lines) >= 2:\n        n = int(lines[0])\n        arr = list(map(int, lines[1].split()))\n        # Write your solution here\n\nif __name__ == '__main__':\n    main()",cpp:"#include <iostream>\n#include <vector>\nusing namespace std;\n\nint main() {\n    int n;\n    if (cin >> n) {\n        vector<int> arr(n);\n        for (int i = 0; i < n; i++) {\n            cin >> arr[i];\n        }\n        // Write your solution here\n    }\n    return 0;\n}"}},

  // ── MEDIUM (10) ──
  { title:"Longest Substring Without Repeating",difficulty:"medium",description:"Given a string, find the length of the longest substring without repeating characters.",tags:["String","Sliding Window"],examples:[{input:"abcabcbb",output:"3"}],testCases:[{input:"abcabcbb",output:"3"},{input:"bbbbb",output:"1"},{input:"pwwkew",output:"3"},{input:"abcdef",output:"6"}],boilerplate:{javascript:"const s=require('fs').readFileSync('/dev/stdin','utf8').trim();\n// Solve here",python:"s=input()\n# Solve here",cpp:"#include<bits/stdc++.h>\nusing namespace std;\nint main(){string s;cin>>s;\n// Solve here\nreturn 0;}"}},
  { title:"Valid Parentheses",difficulty:"medium",description:"Given a string of brackets ()[]{}. Print 'true' if valid, 'false' otherwise.",tags:["Stack","String"],examples:[{input:"()[]{}",output:"true"}],testCases:[{input:"()[]{}",output:"true"},{input:"(]",output:"false"},{input:"([)]",output:"false"},{input:"{[]}",output:"true"},{input:"",output:"true"}],boilerplate:{javascript:"const s=require('fs').readFileSync('/dev/stdin','utf8').trim();\n// Solve here",python:"s=input()\n# Solve here",cpp:"#include<bits/stdc++.h>\nusing namespace std;\nint main(){string s;getline(cin,s);\n// Solve here\nreturn 0;}"}},
  { title:"Merge Two Sorted Arrays",difficulty:"medium",description:"Given two sorted arrays, merge them into one sorted array. Print space-separated.",tags:["Array","Two Pointers"],examples:[{input:"3\n1 3 5\n3\n2 4 6",output:"1 2 3 4 5 6"}],testCases:[{input:"3\n1 3 5\n3\n2 4 6",output:"1 2 3 4 5 6"},{input:"2\n1 2\n2\n3 4",output:"1 2 3 4"},{input:"1\n5\n1\n1",output:"1 5"}],boilerplate:{javascript:"const lines=require('fs').readFileSync('/dev/stdin','utf8').trim().split('\\n');\n// Solve here",python:"import sys\nlines=sys.stdin.read().strip().split('\\n')\n# Solve here",cpp:"#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n// Solve here\nreturn 0;}"}},
  { title:"Binary Search",difficulty:"medium",description:"Given a sorted array and target, print the index (0-based) or -1 if not found.",tags:["Array","Binary Search"],examples:[{input:"5\n1 3 5 7 9\n5",output:"2"}],testCases:[{input:"5\n1 3 5 7 9\n5",output:"2"},{input:"5\n1 3 5 7 9\n6",output:"-1"},{input:"1\n42\n42",output:"0"}],boilerplate:{javascript:"const lines=require('fs').readFileSync('/dev/stdin','utf8').trim().split('\\n');\n// Solve here",python:"import sys\nlines=sys.stdin.read().strip().split('\\n')\n# Solve here",cpp:"#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n// Solve here\nreturn 0;}"}},
  { title:"Matrix Transpose",difficulty:"medium",description:"Given an NxM matrix, print its transpose.",tags:["Array","Matrix"],examples:[{input:"2 3\n1 2 3\n4 5 6",output:"1 4\n2 5\n3 6"}],testCases:[{input:"2 3\n1 2 3\n4 5 6",output:"1 4\n2 5\n3 6"},{input:"1 1\n5",output:"5"},{input:"2 2\n1 2\n3 4",output:"1 3\n2 4"}],boilerplate:{javascript:"const lines=require('fs').readFileSync('/dev/stdin','utf8').trim().split('\\n');\n// Solve here",python:"import sys\nlines=sys.stdin.read().strip().split('\\n')\n# Solve here",cpp:"#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n// Solve here\nreturn 0;}"}},
  { title:"Rotate Array",difficulty:"medium",description:"Rotate array right by k positions. Print space-separated.",tags:["Array"],examples:[{input:"7\n1 2 3 4 5 6 7\n3",output:"5 6 7 1 2 3 4"}],testCases:[{input:"7\n1 2 3 4 5 6 7\n3",output:"5 6 7 1 2 3 4"},{input:"4\n1 2 3 4\n1",output:"4 1 2 3"},{input:"3\n1 2 3\n0",output:"1 2 3"}],boilerplate:{javascript:"const lines=require('fs').readFileSync('/dev/stdin','utf8').trim().split('\\n');\n// Solve here",python:"import sys\nlines=sys.stdin.read().strip().split('\\n')\n# Solve here",cpp:"#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n// Solve here\nreturn 0;}"}},
  { title:"Group Anagrams",difficulty:"medium",description:"Given n words, group anagrams. Print each group sorted, one per line, groups separated by blank line.",tags:["String","Hash Table"],examples:[{input:"3\neat tea ate",output:"ate eat tea"}],testCases:[{input:"3\neat tea ate",output:"ate eat tea"},{input:"1\nhello",output:"hello"},{input:"4\nlisten silent abc cab",output:"abc cab\nlisten silent"}],boilerplate:{javascript:"const lines=require('fs').readFileSync('/dev/stdin','utf8').trim().split('\\n');\n// Solve here",python:"import sys\nlines=sys.stdin.read().strip().split('\\n')\n# Solve here",cpp:"#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n// Solve here\nreturn 0;}"}},
  { title:"Product of Array Except Self",difficulty:"medium",description:"Given array, print array where each element is product of all others. No division.",tags:["Array"],examples:[{input:"4\n1 2 3 4",output:"24 12 8 6"}],testCases:[{input:"4\n1 2 3 4",output:"24 12 8 6"},{input:"3\n2 3 4",output:"12 8 6"},{input:"2\n0 1",output:"1 0"}],boilerplate:{javascript:"const lines=require('fs').readFileSync('/dev/stdin','utf8').trim().split('\\n');\n// Solve here",python:"import sys\nlines=sys.stdin.read().strip().split('\\n')\n# Solve here",cpp:"#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n// Solve here\nreturn 0;}"}},
  { title:"Spiral Matrix",difficulty:"medium",description:"Print an NxN matrix in spiral order, space-separated.",tags:["Matrix"],examples:[{input:"3\n1 2 3\n4 5 6\n7 8 9",output:"1 2 3 6 9 8 7 4 5"}],testCases:[{input:"3\n1 2 3\n4 5 6\n7 8 9",output:"1 2 3 6 9 8 7 4 5"},{input:"1\n1",output:"1"},{input:"2\n1 2\n3 4",output:"1 2 4 3"}],boilerplate:{javascript:"const lines=require('fs').readFileSync('/dev/stdin','utf8').trim().split('\\n');\n// Solve here",python:"import sys\nlines=sys.stdin.read().strip().split('\\n')\n# Solve here",cpp:"#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n// Solve here\nreturn 0;}"}},
  { title:"Longest Palindromic Substring Length",difficulty:"medium",description:"Given a string, find the length of the longest palindromic substring.",tags:["String","DP"],examples:[{input:"babad",output:"3"}],testCases:[{input:"babad",output:"3"},{input:"cbbd",output:"2"},{input:"a",output:"1"},{input:"racecar",output:"7"}],boilerplate:{javascript:"const s=require('fs').readFileSync('/dev/stdin','utf8').trim();\n// Solve here",python:"s=input()\n# Solve here",cpp:"#include<bits/stdc++.h>\nusing namespace std;\nint main(){string s;cin>>s;\n// Solve here\nreturn 0;}"}},

  // ── HARD (10) ──
  { title:"N-Queens Count",difficulty:"hard",description:"Given N, print the number of distinct solutions to the N-Queens puzzle.",tags:["Backtracking"],examples:[{input:"4",output:"2"}],testCases:[{input:"4",output:"2"},{input:"1",output:"1"},{input:"8",output:"92"}],boilerplate:{javascript:"const n=parseInt(require('fs').readFileSync('/dev/stdin','utf8').trim());\n// Solve here",python:"n=int(input())\n# Solve here",cpp:"#include<bits/stdc++.h>\nusing namespace std;\nint main(){int n;cin>>n;\n// Solve here\nreturn 0;}"}},
  { title:"Longest Increasing Subsequence",difficulty:"hard",description:"Given an array, find the length of the longest strictly increasing subsequence.",tags:["DP","Binary Search"],examples:[{input:"8\n10 9 2 5 3 7 101 18",output:"4"}],testCases:[{input:"8\n10 9 2 5 3 7 101 18",output:"4"},{input:"6\n0 1 0 3 2 3",output:"4"},{input:"1\n7",output:"1"}],boilerplate:{javascript:"const lines=require('fs').readFileSync('/dev/stdin','utf8').trim().split('\\n');\n// Solve here",python:"import sys\nlines=sys.stdin.read().strip().split('\\n')\n# Solve here",cpp:"#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n// Solve here\nreturn 0;}"}},
  { title:"Median of Two Sorted Arrays",difficulty:"hard",description:"Given two sorted arrays, find the median. Print as decimal with 1 digit.",tags:["Binary Search","Array"],examples:[{input:"2\n1 3\n2\n2 4",output:"2.5"}],testCases:[{input:"2\n1 3\n2\n2 4",output:"2.5"},{input:"2\n1 2\n2\n3 4",output:"2.5"},{input:"1\n1\n1\n2",output:"1.5"}],boilerplate:{javascript:"const lines=require('fs').readFileSync('/dev/stdin','utf8').trim().split('\\n');\n// Solve here",python:"import sys\nlines=sys.stdin.read().strip().split('\\n')\n# Solve here",cpp:"#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n// Solve here\nreturn 0;}"}},
  { title:"Word Break",difficulty:"hard",description:"Given string s and dictionary words, print 'true' if s can be segmented into dictionary words.",tags:["DP","String"],examples:[{input:"leetcode\n2\nleet code",output:"true"}],testCases:[{input:"leetcode\n2\nleet code",output:"true"},{input:"applepenapple\n2\napple pen",output:"true"},{input:"catsandog\n5\ncats dog sand and cat",output:"false"}],boilerplate:{javascript:"const lines=require('fs').readFileSync('/dev/stdin','utf8').trim().split('\\n');\n// Solve here",python:"import sys\nlines=sys.stdin.read().strip().split('\\n')\n# Solve here",cpp:"#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n// Solve here\nreturn 0;}"}},
  { title:"Trapping Rain Water",difficulty:"hard",description:"Given n elevation bars, compute trapped rain water.",tags:["Array","Two Pointers"],examples:[{input:"12\n0 1 0 2 1 0 1 3 2 1 2 1",output:"6"}],testCases:[{input:"12\n0 1 0 2 1 0 1 3 2 1 2 1",output:"6"},{input:"6\n4 2 0 3 2 5",output:"9"},{input:"3\n1 0 1",output:"1"}],boilerplate:{javascript:"const lines=require('fs').readFileSync('/dev/stdin','utf8').trim().split('\\n');\n// Solve here",python:"import sys\nlines=sys.stdin.read().strip().split('\\n')\n# Solve here",cpp:"#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n// Solve here\nreturn 0;}"}},
  { title:"Merge K Sorted Lists",difficulty:"hard",description:"Given k sorted arrays, merge into one sorted array. Print space-separated.",tags:["Heap","Divide and Conquer"],examples:[{input:"3\n3\n1 4 5\n3\n1 3 4\n2\n2 6",output:"1 1 2 3 4 4 5 6"}],testCases:[{input:"3\n3\n1 4 5\n3\n1 3 4\n2\n2 6",output:"1 1 2 3 4 4 5 6"},{input:"1\n3\n1 2 3",output:"1 2 3"},{input:"2\n1\n1\n1\n2",output:"1 2"}],boilerplate:{javascript:"const lines=require('fs').readFileSync('/dev/stdin','utf8').trim().split('\\n');\n// Solve here",python:"import sys\nlines=sys.stdin.read().strip().split('\\n')\n# Solve here",cpp:"#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n// Solve here\nreturn 0;}"}},
  { title:"Minimum Window Substring",difficulty:"hard",description:"Given strings s and t, find minimum window in s containing all chars of t. Print the substring or empty string.",tags:["Sliding Window","Hash Table"],examples:[{input:"ADOBECODEBANC\nABC",output:"BANC"}],testCases:[{input:"ADOBECODEBANC\nABC",output:"BANC"},{input:"a\na",output:"a"},{input:"a\naa",output:""}],boilerplate:{javascript:"const lines=require('fs').readFileSync('/dev/stdin','utf8').trim().split('\\n');\n// Solve here",python:"import sys\nlines=sys.stdin.read().strip().split('\\n')\n# Solve here",cpp:"#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n// Solve here\nreturn 0;}"}},
  { title:"Edit Distance",difficulty:"hard",description:"Given two strings, find the minimum number of operations (insert, delete, replace) to convert one to another.",tags:["DP","String"],examples:[{input:"horse\nros",output:"3"}],testCases:[{input:"horse\nros",output:"3"},{input:"intention\nexecution",output:"5"},{input:"abc\nabc",output:"0"}],boilerplate:{javascript:"const lines=require('fs').readFileSync('/dev/stdin','utf8').trim().split('\\n');\n// Solve here",python:"import sys\nlines=sys.stdin.read().strip().split('\\n')\n# Solve here",cpp:"#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n// Solve here\nreturn 0;}"}},
  { title:"Serialize Binary Tree",difficulty:"hard",description:"Given a level-order binary tree (null for empty), print the preorder traversal space-separated.",tags:["Tree","BFS"],examples:[{input:"1 2 3 null null 4 5",output:"1 2 3 4 5"}],testCases:[{input:"1 2 3 null null 4 5",output:"1 2 3 4 5"},{input:"1",output:"1"},{input:"1 2 null",output:"1 2"}],boilerplate:{javascript:"const s=require('fs').readFileSync('/dev/stdin','utf8').trim();\n// Solve here",python:"s=input()\n# Solve here",cpp:"#include<bits/stdc++.h>\nusing namespace std;\nint main(){string line;getline(cin,line);\n// Solve here\nreturn 0;}"}},
  { title:"Maximum Subarray Sum (Kadane's)",difficulty:"hard",description:"Given an array of integers, find the contiguous subarray with the largest sum.",tags:["Array","DP"],examples:[{input:"9\n-2 1 -3 4 -1 2 1 -5 4",output:"6"}],testCases:[{input:"9\n-2 1 -3 4 -1 2 1 -5 4",output:"6"},{input:"1\n1",output:"1"},{input:"5\n-1 -2 -3 -4 -5",output:"-1"}],boilerplate:{javascript:"const lines=require('fs').readFileSync('/dev/stdin','utf8').trim().split('\\n');\n// Solve here",python:"import sys\nlines=sys.stdin.read().strip().split('\\n')\n# Solve here",cpp:"#include<bits/stdc++.h>\nusing namespace std;\nint main(){\n// Solve here\nreturn 0;}"}}
]

async function seed() {
  try {
    await connectDB()
    
    // Use --force flag to force re-seed: node seedProblems.js --force
    const forceReseed = process.argv.includes("--force")
    
    const count = await Problem.countDocuments()
    if (count >= 30 && !forceReseed) {
      console.log(`DB already has ${count} problems. Skipping seed. (use --force to re-seed)`)
      process.exit(0)
    }
    if (count > 0) {
      console.log(`Clearing ${count} existing problems and re-seeding...`)
      await Problem.deleteMany({})
    }
    await Problem.insertMany(problems)
    console.log(`Seeded ${problems.length} problems successfully!`)
    process.exit(0)
  } catch (err) {
    console.error("Seed failed:", err.message)
    process.exit(1)
  }
}

seed()